### ISSUE TITLE
Any performance numbers? 

### ISSUE THREAD

**Issue by LifeIsStrange** [bagder/HTTP3-test#7]

**Comment by bagder** [comment]
I'm not aware of any public reliable performance numbers from any implemenations.

**Comment by LifeIsStrange** [comment]
@badger I find it worrying, could it be that HTTP3 has been officially said to be based on quic prematurely? And that quic is inherently flawed to be a performance regression over http2 in some fundamental workloads?

**Comment by LifeIsStrange** [comment]
When do you think HTTP3 will be released?

**Comment by LifeIsStrange** [comment]
Closing an issue does not help to resolve it, actually quite the reverse.
HTTP 3 without performance guarantees is pointless and therefore is this repository.

**Comment by bagder** [comment]
Closing this issue means there won't be any performance numbers added to this list of HTTP/3 servers. That's what I host in this repo. If you want performance numbers added here, then I suggest you instead start getting some and provide a PR with them instead.
